### ISSUE TITLE
Architektur abbilden

### ISSUE THREAD

**Issue by pokgak** [pokgak/cloud-wp-ws19#2]
![WhatsApp Image 2019-10-01 at 13 54 19](https://user-images.githubusercontent.com/20373062/65959969-a39e7480-e453-11e9-88b8-c4f23967e8d3.jpeg)

**Comment by pokgak** [comment]
Old version #1

**Comment by pokgak** [comment]
Closes #1

**Comment by mohammadfazelsoltani** [comment]
![Microservice Architektur Version 1](https://user-images.githubusercontent.com/35668340/65982273-40283d00-e47b-11e9-8a79-37d149bf57f3.png)

**Comment by mohammadfazelsoltani** [comment]
@pokgak und @DennisSentler 
Ich habe unsere erarbeitete Architektur etwas grafisch "verschönert".
Wäre gut, wenn ihr euch das nochmal anguckt und ggf. Feedback dazu gibt.
Ich werde dann die Task schließen, wenn ihr beide damit einverstanden seit.

**Comment by pokgak** [comment]
Sieht gut aus! Nur eine Sache: ich habe gefunden wie die Public API eigentlich heissen soll: Reverse Proxy. Die API Schnittstelle (kleine Kästchen)  für die Reverse Proxy kann dann auch weg, weil die keine eigene API bietet sondern nur "proxy" zu den backend services.

Mehr zum reverse proxies: https://dzone.com/articles/why-proxies-are-important-for-microservices

**Comment by DennisSentler** [comment]
Die API von dem Reverse Proxy ist aber auch keine API für die Backend Servicces sondern für die UI bzw den Kunden

**Comment by mohammadfazelsoltani** [comment]
![Microservice Architektur Version 1 1](https://user-images.githubusercontent.com/35668340/66135580-75a76480-e5fa-11e9-85b5-e661db177c74.png)

**Comment by mohammadfazelsoltani** [comment]
@pokgak @DennisSentler 
Habe es nochmal angepasst.
Ich bitte euch erneut mal drauf zu schauen!

**Comment by mohammadfazelsoltani** [comment]
![Microservice Architektur Version 1 2](https://user-images.githubusercontent.com/35668340/66206886-a9919100-e6b1-11e9-84b2-02c8ecbba908.png)

**Comment by pokgak** [comment]
Änderung nach Diskussion: Auth und User jetzt in einem Service
