### ISSUE TITLE
Hello World in der Cloud

### ISSUE THREAD

**Issue by pokgak** [pokgak/cloud-wp-ws19#3]

**Comment by DennisSentler** [comment]
So, ich habe eine Beispielanwendung innerhalb eines Containers unter GCP deployed.
Dokuemntation dazu befindet sich in unserem Wiki: [Helloworld auf GCP](https://github.com/pokgak/cloud-wp-ws19/wiki/Helloworld-auf-GCP)

**Comment by mohammadfazelsoltani** [comment]
@DennisSentler 
Wäre nett, wenn du mir das mal in einer Live-Demo zeigen könntest 🙈
